DROP TABLE  IF EXISTS amazon;

CREATE TABLE amazon(
 order_id INTEGER PRIMARY KEY,
 order_date DATE,
 product_name VARCHAR (100),
 category VARCHAR (150),
 region VARCHAR (10),
 quantity INTEGER ,
 sales INTEGER,
 profit NUMERIC (8,2)
 
);

-- Data exploration--

-- Count of rows
SELECT COUNT(*) FROM amazon;

-- sample data.
SELECT * FROM amazon 
LIMIT 10;

-- NULL values.
SELECT * FROM amazon
WHERE product_name IS NULL
OR
order_date IS NULL
OR
category IS NULL
OR
region IS NULL
OR
quantity IS NULL
OR
sales IS NULL
OR
profit IS NULL;

-- Different product categories.

SELECT DISTINCT category FROM amazon
ORDER BY category;


-- Products names present multiple time
SELECT product_name , COUNT(order_id) AS No_of_order FROM amazon
GROUP BY product_name
HAVING COUNT(order_id) >1
ORDER BY COUNT(order_id)  DESC;

-- Data Cleaning.--

--How many missing values exist in each column of the dataset

SELECT
COUNT(*) AS total_rows,
COUNT(sales) AS sales_not_null,
COUNT(profit) AS profit_not_null,
COUNT(quantity) AS quantity_not_null,
COUNT(region) AS region_not_null
FROM amazon;

--Identify Duplicate Records

SELECT
order_date,
product_name,
region,
COUNT(*) AS duplicate_count
FROM amazon
GROUP BY
order_date,
product_name,
region
HAVING COUNT(*) > 1;

--Check for Negative Values
SELECT *
FROM amazon
WHERE sales < 0
   OR quantity < 0
   OR profit < 0;

-- Check for Zero Quantity
SELECT *
FROM amazon
WHERE quantity = 0;



--1. How many total records are present in the amazon dataset?

SELECT COUNT(*) AS Total_record
FROM amazon;

--2.What are the unique regions available in the dataset?

SELECT DISTINCT region
FROM amazon;

--3.What is the total sales generated by the business?

SELECT sum(sales) AS Total_sales
FROM amazon;

--4. What is the total profit earned by the business?

SELECT SUM(profit)AS Total_profit
FROM amazon;

--5.What is the total quantity of products sold?

SELECT SUM(quantity) AS Total_quantity
FROM amazon;

--6.What is the total sales generated in each region?

SELECT region , SUM(sales) AS Total_sales
FROM amazon
GROUP BY region
ORDER BY Total_sales DESC;

--7.What is the total profit generated in each category?

SELECT category , SUM(profit) AS Total_profit
FROM amazon
GROUP BY category
ORDER BY Total_profit DESC;

--8.Which are the top 5 products based on total sales?
SELECT product_name, SUM(sales)AS Total_sales
FROM amazon
GROUP BY product_name
ORDER BY Total_sales Desc
LIMIT 5;

--9.What is the average sales value per order?

SELECT ROUND(AVG(sales),2) AS Avg_sales
FROM amazon

--10.What is the total sales for each month?

SELECT 
       EXTRACT(MONTH FROM order_date) AS month,
       SUM(sales) AS total_sales
FROM amazon
GROUP BY EXTRACT(MONTH FROM order_date)
ORDER BY month;

--11.Which products are generating negative profit?

SELECT DISTINCT product_name
FROM amazon
WHERE profit < 0;

--12.Which products have high sales but low profit?

SELECT product_name,
 SUM(sales) AS total_sales,
 SUM(profit) AS total_profit
 FROM amazon
 GROUP BY product_name
 HAVING SUM(sales) > 1000
  AND SUM(profit) < 100
  ORDER BY total_sales DESC;

--13.What is the profit margin for each category?

SELECT category ,
ROUND(SUM(profit)/ SUM(sales)* 100,2) AS profit_margin
FROM amazon
GROUP BY category
ORDER BY profit_margin DESC;

--14.Which region generates the highest total profit?

SELECT region , SUM(profit) AS total_profit
FROM amazon
GROUP BY region
ORDER BY total_profit DESC
LIMIT 1;

--15.What percentage of total sales is contributed by each category?

SELECT 
    category,
    SUM(sales) AS category_sales,
    ROUND(
        SUM(sales) * 100.0 / 
        (SELECT SUM(sales) FROM amazon),
        2
    ) AS sales_percentage
FROM amazon
GROUP BY category
ORDER BY sales_percentage DESC;